const data ={
   products: [
      {
          _id:'1',
          name:'Pant',
          category:'Shirt',
          image:'/images/p1.jpg',
          price:120,
          brand:'Nike',
          rating:4.5,
          numReviews:10,
          description:'high quality product',
      },
      {
        _id:'2',
        name:'Shirt',
        category:'Shirt',
        image:'/images/p1.jpg',
        price:120,
        brand:'Nike',
        rating:4.5,
        numReviews:10,
        description:'high quality product',
    },
    {
        _id:'3',
        name:'Pajama',
        category:'Pant',
        image:'/images/p1.jpg',
        price:220,
        brand:'Nike',
        rating:4.5,
        numReviews:10,
        description:'high quality product',
    },
    {
        _id:'4',
        name:'Under wear',
        category:'Pant',
        image:'/images/p1.jpg',
        price:520,
        brand:'Nike',
        rating:4.5,
        numReviews:10,
        description:'high quality product',
    },
    {
        _id:'5',
        name:'Bleaser',
        category:'Shirt',
        image:'/images/p1.jpg',
        price:233,
        brand:'Nike',
        rating:4.5,
        numReviews:10,
        description:'high quality product',
    }
    ],
};
export default data;